{% set name = "File-Which" %}
{% set version = "1.24" %}

package:
  name: perl-{{ name|lower }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/{{ name }}-{{ version }}.tar.gz
  sha256: 7c5414dd6d5c61cb992fdd257aefe52f9a80bf55158cd5ec17469199d0b12eef

build:
  number: 0
  noarch: generic
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
  run:
    - perl

test:
  imports:
    - File::Which

about:
  home: https://metacpan.org/release/{{ name }}
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  license_file: LICENSE
  summary: Perl implementation of the which utility as an API

extra:
  recipe-maintainers:
    - tdegeus
